# src/main/resources/application-dev.yml
# Se activa cuando spring.profiles.active=dev

spring:
  datasource:
    # Puerto 3307 porque así lo configuramos en docker-compose.yml
    url: jdbc:mysql://localhost:3307/sistema_cursos_fhce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/La_Paz
    username: fhce_user
    password: fhce_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ramos.e.kasandra@gmail.com          # ← tu cuenta Gmail
    password: uieo ejtb udjp zyhc          # ← contraseña de aplicación (sin espacios)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
# En dev: mostrar SQL y usar mocks
logging:
  level:
    bo.edu.umsa.fhce: DEBUG        # logs detallados de nuestro código
    org.hibernate.SQL: DEBUG       # queries SQL
    org.hibernate.type: TRACE     # valores de parámetros en las queries

# Indicador del perfil activo (útil para saber qué mock está cargado)
app:
  mocks:
    umsa-auth: true     # UmsaAuthClient usará implementación mock
    libelula-pay: true  # LilaPayClient usará implementación mock
  email:
    # URL base para links en emails (en prod cambiar al dominio real)
    base-url: "http://localhost:5173"

