# src/main/resources/application-dev.yml
# Se activa cuando spring.profiles.active=dev

spring:
  datasource:
    # Puerto 3307 porque así lo configuramos en docker-compose.yml
    url: jdbc:mysql://localhost:3307/sistema_cursos_fhce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/La_Paz
    username: fhce_user
    password: fhce_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b02c0e353f0479
    password: f530b6065a3a3d
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# En dev: mostrar SQL y usar mocks
logging:
  level:
    bo.edu.umsa.fhce: DEBUG        # logs detallados de nuestro código
    org.hibernate.SQL: DEBUG       # queries SQL
    org.hibernate.type: TRACE     # valores de parámetros en las queries

# Indicador del perfil activo (útil para saber qué mock está cargado)
app:
  mocks:
    umsa-auth: true     # UmsaAuthClient usará implementación mock
    libelula-pay: true  # LilaPayClient usará implementación mock
  email:
    from: "noreply@fhce.umsa.bo"
    # URL base para links en emails (en prod cambiar al dominio real)
    base-url: "http://localhost:5173"

